server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  server:
    enable-self-preservation: ${EUREKA_ENABLE_SELF_PRESERVATION:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized

info:
  app:
    name: eureka-server
    service: eureka-server
